name: Laravel CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate deployment package
        run: zip -r deploy.zip ./
      
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "New PHPUnit Test"
          environment_name: "NewPHPUnitTest-env"
          existing_bucket_name: elasticbeanstalk-ap-southeast-2-875607159810
          version_label: ${{ github.sha }}
          region: ap-southeast-2
          deployment_package: deploy.zip

  # docker:
  #   # needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@v3
  #       with:
  #         context: .
  #         push: true
  #         build-args: |
  #           REPO_NAME=${{ github.event.repository.name }}
  #         tags: |
  #           ${{ secrets.DOCKERHUB_USERNAME }}/laravel-phpunit-test:latest
  #           ${{ secrets.DOCKERHUB_USERNAME }}/laravel-phpunit-test:${{ github.sha }}