name: Laravel CI Pipeline

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, sqlite3
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-progress --no-interaction --prefer-dist

      - name: Install Node.js dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install

      - name: Set up SQLite database
        run: |
          mkdir -p database
          touch database/database.sqlite
          cp .env.example .env
          php artisan key:generate
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=/home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/database/database.sqlite" >> .env
          echo "SESSION_DRIVER=array" >> .env
          echo "CACHE_DRIVER=array" >> .env

      - name: Ensure storage & cache directories are writable
        run: |
          chmod -R 777 storage bootstrap/cache

      - name: Configure database
        run: |
          php artisan config:clear
          php artisan migrate:fresh --seed --force

      - name: Wait for Laravel to boot
        run: sleep 3

      - name: Run PHPUnit tests
        run: php artisan test
